<a href="https://colab.research.google.com/github/agu3ro/Pytorch-DL/blob/main/Tensors_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import torch

In [15]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# RESHAPE VS VIEW

In [16]:
my_torch_1 = my_torch.reshape(5,2)
my_torch_1

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

We can also reshape if we dont know how many items are in there using -1 (BUT STILL NUMBERS BEFORE SHOULD MAKE SENSE WHEN MULTIPLYING)

In [17]:
my_torch_2 = torch.arange(10)
my_torch_2 = my_torch_2.reshape(2,-1)
my_torch_2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
my_torch_3 = torch.arange(10)
my_torch_4 = my_torch_3.view(2,-1)
my_torch_4


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# with reshape and view they will update
# (as in view, reshape also makes tensors linked)

In [19]:
my_torch_5 = torch.arange(10)
my_torch_5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_torch_6 = my_torch_5.reshape(2,5)
my_torch_6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [25]:
my_torch_5[1] = 1488
print(my_torch_5)
print(my_torch_6)

tensor([   0, 1488,    2,    3,    4, 1488, 1488, 1488, 1488, 1488])
tensor([[   0, 1488,    2,    3,    4],
        [1488, 1488, 1488, 1488, 1488]])


# Slices

In [39]:
my_torch_7 = torch.arange(14)
# Grab a specific item
my_torch_7[7]

tensor(7)

In [41]:
# Grab Slice
my_torch_8 = my_torch_7.reshape(7,2)
my_torch_8

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13]])

In [43]:
my_torch_8[:,1]

tensor([ 1,  3,  5,  7,  9, 11, 13])

Return column

In [44]:
my_torch_8[:,1:] # : = all rows; 1: - all columns after the 1st one

tensor([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13]])