<a href="https://colab.research.google.com/github/agu3ro/Pytorch-DL/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np



### Lists

In [3]:
my_list = [1,2,3,4,5]
my_list_2 = [[1,2,3,4,5],[6,7,8,9,10]]
print(my_list)
print(my_list_2)

[1, 2, 3, 4, 5]
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


## NumPy array

In [4]:
np1 = np.random.rand(3,4)
print(np1)

[[0.20004232 0.88588836 0.71309925 0.65699878]
 [0.02109382 0.44178612 0.35882893 0.87810206]
 [0.599937   0.40969353 0.26794507 0.28579695]]


## TENSORS

In [5]:
tensor_2d = torch.randn(3,4)
print(tensor_2d)

tensor_3d = torch.zeros(2,3,4) # 2nd number is how many dimensionals
print(tensor_3d)

tensor([[-0.1653, -0.0291,  0.5773,  0.2421],
        [ 0.8029,  0.4478,  1.0126,  1.4139],
        [ 0.3375,  1.4161,  0.4938, -0.8461]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


Create TENSOR out of NumPy array

In [6]:
tensor_copy = torch.Tensor(np1)
tensor_copy

tensor([[0.2000, 0.8859, 0.7131, 0.6570],
        [0.0211, 0.4418, 0.3588, 0.8781],
        [0.5999, 0.4097, 0.2679, 0.2858]])