<a href="https://colab.research.google.com/github/agu3ro/Pytorch-DL/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [13]:
tensor_1 = torch.tensor([1,2,3,4])
tensor_2 = torch.tensor([5,6,7,8])

In [14]:
tensor_2 - tensor_1

tensor([4, 4, 4, 4])

In [21]:
tensor_1.sub(tensor_2)

tensor([-4, -4, -4, -4])

In [16]:
tensor_2.mul(tensor_1)

tensor([ 5, 12, 21, 32])

In [22]:
# Remainder
tensor_2 % tensor_1

tensor([0, 0, 1, 0])

In [23]:
torch.remainder(tensor_2, tensor_1)

tensor([0, 0, 1, 0])

In [24]:
# POwer
torch.pow(tensor_2, tensor_1)

tensor([   5,   36,  343, 4096])

In [25]:
tensor_2 ** tensor_1

tensor([   5,   36,  343, 4096])

In [18]:
tensor_2.div(tensor_1)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [9]:
tensor_2.add_(tensor_1)

tensor([ 6,  8, 10, 12])

In [10]:
tensor_1

tensor([1, 2, 3, 4])

In [11]:
tensor_2

tensor([ 6,  8, 10, 12])